# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0.xci
# IP: The module: 'hdmi_out_axi_gpio_sw_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_sw_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_sw_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_sw_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0.xci
# IP: The module: 'hdmi_out_axi_gpio_sw_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_sw_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_sw_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xil_prj/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/hdmi_out_axi_gpio_sw_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_gpio_sw_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
