#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Sun Nov 19 11:47:54 +0300 2023
# SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : hdmi_out.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : hdmi_out.sh
#                hdmi_out.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                hdmi_out.sh [-reset_run]
#                hdmi_out.sh [-reset_log]
#                hdmi_out.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'hdmi_out.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname lib_cdc_v1_0_2 -libname lib_pkg_v1_0_3 -libname fifo_generator_v13_2_9 -libname lib_fifo_v1_0_18 -libname blk_mem_gen_v8_4_7 -libname lib_bmg_v1_0_16 -libname lib_srl_fifo_v1_0_3 -libname axi_datamover_v5_1_31 -libname axi_vdma_v6_3_17 -libname axis_infrastructure_v1_1_1 -libname axis_register_slice_v1_1_29 -libname axis_subset_converter_v1_1_29 -libname generic_baseblocks_v2_1_1 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_29 -libname axi_data_fifo_v2_1_28 -libname axi_crossbar_v2_1_30 -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_1_13 -libname v_vid_in_axi4s_v4_0_11 -libname v_axi4s_vid_out_v4_0_17 -libname v_tc_v6_2_7 -libname xlconcat_v2_1_5 -libname xlconstant_v1_1_8 -libname interrupt_control_v3_1_5 -libname axi_gpio_v2_0_31 -libname proc_sys_reset_v5_0_14 -libname axi_vip_v1_1_15 -libname processing_system7_vip_v1_0_17 -libname gigantic_mux -libname axi_protocol_converter_v2_1_29 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib lib_cdc_v1_0_2 lib_pkg_v1_0_3 fifo_generator_v13_2_9 lib_fifo_v1_0_18 blk_mem_gen_v8_4_7 lib_bmg_v1_0_16 lib_srl_fifo_v1_0_3 axi_datamover_v5_1_31 axi_vdma_v6_3_17 axis_infrastructure_v1_1_1 axis_register_slice_v1_1_29 axis_subset_converter_v1_1_29 generic_baseblocks_v2_1_1 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_29 axi_data_fifo_v2_1_28 axi_crossbar_v2_1_30 axi_lite_ipif_v3_0_4 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_17 v_tc_v6_2_7 xlconcat_v2_1_5 xlconstant_v1_1_8 interrupt_control_v3_1_5 axi_gpio_v2_0_31 proc_sys_reset_v5_0_14 axi_vip_v1_1_15 processing_system7_vip_v1_0_17 gigantic_mux axi_protocol_converter_v2_1_29)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "hdmi_out.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./hdmi_out.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "C:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/2a7c/src/mmcme2_drp.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/2a7c/src/SyncAsync.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/2a7c/src/axi_dynclk_S00_AXI.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/2a7c/src/axi_dynclk.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axi_dynclk_0_0/sim/hdmi_out_axi_dynclk_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_3 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_9 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_18 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_7 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_bmg_v1_0_16 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/5c9c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_3 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_31 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_vdma_v6_3_17 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_vdma_v6_3_17 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/sim/hdmi_out_axi_vdma_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_register_slice_v1_1_29 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/af18/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tdata_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tuser_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tstrb_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tkeep_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tid_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tdest_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tlast_hdmi_out_axis_subset_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_subset_converter_v1_1_29 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0f24/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/top_hdmi_out_axis_subset_converter_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/sim/hdmi_out_axis_subset_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_1 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_28 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_30 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_xbar_0/sim/hdmi_out_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/ClockGen.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/SyncAsync.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/SyncAsyncReset.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/DVI_Constants.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/OutputSERDES.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/TMDS_Encoder.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d57c/src/rgb2dvi.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/sim/hdmi_out_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_13 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_11 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_17 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/b7a6/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/sim/hdmi_out_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_7 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e63/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/sim/hdmi_out_v_tc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_5 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_xlconcat_0_0/sim/hdmi_out_xlconcat_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_8 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_xlconstant_0_0/sim/hdmi_out_xlconstant_0_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_xlconstant_1_0/sim/hdmi_out_xlconstant_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_31 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6fbe/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_btn_0/sim/hdmi_out_axi_gpio_btn_0.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/sim/hdmi_out_axi_gpio_hdmi_0.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_led_0/sim/hdmi_out_axi_gpio_led_0.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_sw_0/sim/hdmi_out_axi_gpio_sw_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/sim/hdmi_out_proc_sys_reset_0_0.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/sim/hdmi_out_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_17 $xmvlog_opts -sv +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/sim/hdmi_out_processing_system7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_system_ila_0_0/bd_0/sim/bd_8245.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_system_ila_0_0/bd_0/ip/ip_0/sim/bd_8245_ila_lib_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work gigantic_mux $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_system_ila_0_0/bd_0/ip/ip_1/bd_8245_g_inst_0_gigantic_mux.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_system_ila_0_0/bd_0/ip/ip_1/sim/bd_8245_g_inst_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_system_ila_0_0/sim/hdmi_out_system_ila_0_0.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/69dc/src/rgb2vga.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2vga_0_0/sim/hdmi_out_rgb2vga_0_0.vhd" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_rgb_doubler_0_1/sim/hdmi_out_rgb_doubler_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_s00_regslice_0/sim/hdmi_out_s00_regslice_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_s00_data_fifo_0/sim/hdmi_out_s00_data_fifo_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_29 $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/7fb4/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/434f/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ec67/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/6b2b/hdl" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/e2ba/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/a29c/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/ae90/hdl/verilog" +incdir+"../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ipshared/0e59/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_0/sim/hdmi_out_auto_pc_0.v" \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_1/sim/hdmi_out_auto_pc_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../hdmi_out.gen/sources_1/bd/hdmi_out/sim/hdmi_out.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.hdmi_out xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.hdmi_out -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log hdmi_out_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./hdmi_out.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: hdmi_out.sh [-help]\n\
Usage: hdmi_out.sh [-step]\n\
Usage: hdmi_out.sh [-lib_map_path]\n\
Usage: hdmi_out.sh [-reset_run]\n\
Usage: hdmi_out.sh [-reset_log]\n\
Usage: hdmi_out.sh [-keep_index]\n\
Usage: hdmi_out.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
