-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hdmi_out_v_tpg_0_0_entry_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    field_id_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
    field_id_val8_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    field_id_val8_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    field_id_val8_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    field_id_val8_c_full_n : IN STD_LOGIC;
    field_id_val8_c_write : OUT STD_LOGIC;
    fid_in_val9 : IN STD_LOGIC_VECTOR (0 downto 0);
    fid_in_val9_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    fid_in_val9_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    fid_in_val9_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    fid_in_val9_c_full_n : IN STD_LOGIC;
    fid_in_val9_c_write : OUT STD_LOGIC;
    ovrlayId_val11 : IN STD_LOGIC_VECTOR (7 downto 0);
    ovrlayId_val11_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    ovrlayId_val11_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ovrlayId_val11_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ovrlayId_val11_c_full_n : IN STD_LOGIC;
    ovrlayId_val11_c_write : OUT STD_LOGIC;
    maskId_val12 : IN STD_LOGIC_VECTOR (7 downto 0);
    maskId_val12_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    maskId_val12_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    maskId_val12_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    maskId_val12_c_full_n : IN STD_LOGIC;
    maskId_val12_c_write : OUT STD_LOGIC;
    crossHairX_val18 : IN STD_LOGIC_VECTOR (15 downto 0);
    crossHairX_val18_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    crossHairX_val18_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    crossHairX_val18_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    crossHairX_val18_c_full_n : IN STD_LOGIC;
    crossHairX_val18_c_write : OUT STD_LOGIC;
    crossHairY_val19 : IN STD_LOGIC_VECTOR (15 downto 0);
    crossHairY_val19_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    crossHairY_val19_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    crossHairY_val19_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    crossHairY_val19_c_full_n : IN STD_LOGIC;
    crossHairY_val19_c_write : OUT STD_LOGIC;
    boxSize_val24 : IN STD_LOGIC_VECTOR (15 downto 0);
    boxSize_val24_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxSize_val24_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    boxSize_val24_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    boxSize_val24_c_full_n : IN STD_LOGIC;
    boxSize_val24_c_write : OUT STD_LOGIC;
    boxColorR_val25 : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorR_val25_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    boxColorR_val25_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    boxColorR_val25_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    boxColorR_val25_c_full_n : IN STD_LOGIC;
    boxColorR_val25_c_write : OUT STD_LOGIC;
    boxColorG_val26 : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorG_val26_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    boxColorG_val26_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    boxColorG_val26_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    boxColorG_val26_c_full_n : IN STD_LOGIC;
    boxColorG_val26_c_write : OUT STD_LOGIC;
    boxColorB_val27 : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorB_val27_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    boxColorB_val27_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    boxColorB_val27_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    boxColorB_val27_c_full_n : IN STD_LOGIC;
    boxColorB_val27_c_write : OUT STD_LOGIC );
end;


architecture behav of hdmi_out_v_tpg_0_0_entry_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal field_id_val8_c_blk_n : STD_LOGIC;
    signal fid_in_val9_c_blk_n : STD_LOGIC;
    signal ovrlayId_val11_c_blk_n : STD_LOGIC;
    signal maskId_val12_c_blk_n : STD_LOGIC;
    signal crossHairX_val18_c_blk_n : STD_LOGIC;
    signal crossHairY_val19_c_blk_n : STD_LOGIC;
    signal boxSize_val24_c_blk_n : STD_LOGIC;
    signal boxColorR_val25_c_blk_n : STD_LOGIC;
    signal boxColorG_val26_c_blk_n : STD_LOGIC;
    signal boxColorB_val27_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, field_id_val8_c_full_n, fid_in_val9_c_full_n, ovrlayId_val11_c_full_n, maskId_val12_c_full_n, crossHairX_val18_c_full_n, crossHairY_val19_c_full_n, boxSize_val24_c_full_n, boxColorR_val25_c_full_n, boxColorG_val26_c_full_n, boxColorB_val27_c_full_n)
    begin
                ap_block_state1 <= ((boxColorG_val26_c_full_n = ap_const_logic_0) or (boxColorR_val25_c_full_n = ap_const_logic_0) or (boxSize_val24_c_full_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (crossHairY_val19_c_full_n = ap_const_logic_0) or (crossHairX_val18_c_full_n = ap_const_logic_0) or (maskId_val12_c_full_n = ap_const_logic_0) or (ovrlayId_val11_c_full_n = ap_const_logic_0) or (fid_in_val9_c_full_n = ap_const_logic_0) or (field_id_val8_c_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (boxColorB_val27_c_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    boxColorB_val27_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, boxColorB_val27_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            boxColorB_val27_c_blk_n <= boxColorB_val27_c_full_n;
        else 
            boxColorB_val27_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    boxColorB_val27_c_din <= boxColorB_val27;

    boxColorB_val27_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            boxColorB_val27_c_write <= ap_const_logic_1;
        else 
            boxColorB_val27_c_write <= ap_const_logic_0;
        end if; 
    end process;


    boxColorG_val26_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, boxColorG_val26_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            boxColorG_val26_c_blk_n <= boxColorG_val26_c_full_n;
        else 
            boxColorG_val26_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    boxColorG_val26_c_din <= boxColorG_val26;

    boxColorG_val26_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            boxColorG_val26_c_write <= ap_const_logic_1;
        else 
            boxColorG_val26_c_write <= ap_const_logic_0;
        end if; 
    end process;


    boxColorR_val25_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, boxColorR_val25_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            boxColorR_val25_c_blk_n <= boxColorR_val25_c_full_n;
        else 
            boxColorR_val25_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    boxColorR_val25_c_din <= boxColorR_val25;

    boxColorR_val25_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            boxColorR_val25_c_write <= ap_const_logic_1;
        else 
            boxColorR_val25_c_write <= ap_const_logic_0;
        end if; 
    end process;


    boxSize_val24_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, boxSize_val24_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            boxSize_val24_c_blk_n <= boxSize_val24_c_full_n;
        else 
            boxSize_val24_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    boxSize_val24_c_din <= boxSize_val24;

    boxSize_val24_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            boxSize_val24_c_write <= ap_const_logic_1;
        else 
            boxSize_val24_c_write <= ap_const_logic_0;
        end if; 
    end process;


    crossHairX_val18_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, crossHairX_val18_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            crossHairX_val18_c_blk_n <= crossHairX_val18_c_full_n;
        else 
            crossHairX_val18_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    crossHairX_val18_c_din <= crossHairX_val18;

    crossHairX_val18_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            crossHairX_val18_c_write <= ap_const_logic_1;
        else 
            crossHairX_val18_c_write <= ap_const_logic_0;
        end if; 
    end process;


    crossHairY_val19_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, crossHairY_val19_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            crossHairY_val19_c_blk_n <= crossHairY_val19_c_full_n;
        else 
            crossHairY_val19_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    crossHairY_val19_c_din <= crossHairY_val19;

    crossHairY_val19_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            crossHairY_val19_c_write <= ap_const_logic_1;
        else 
            crossHairY_val19_c_write <= ap_const_logic_0;
        end if; 
    end process;


    fid_in_val9_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, fid_in_val9_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fid_in_val9_c_blk_n <= fid_in_val9_c_full_n;
        else 
            fid_in_val9_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    fid_in_val9_c_din <= fid_in_val9;

    fid_in_val9_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            fid_in_val9_c_write <= ap_const_logic_1;
        else 
            fid_in_val9_c_write <= ap_const_logic_0;
        end if; 
    end process;


    field_id_val8_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, field_id_val8_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            field_id_val8_c_blk_n <= field_id_val8_c_full_n;
        else 
            field_id_val8_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    field_id_val8_c_din <= field_id_val8;

    field_id_val8_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            field_id_val8_c_write <= ap_const_logic_1;
        else 
            field_id_val8_c_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    maskId_val12_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, maskId_val12_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            maskId_val12_c_blk_n <= maskId_val12_c_full_n;
        else 
            maskId_val12_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    maskId_val12_c_din <= maskId_val12;

    maskId_val12_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            maskId_val12_c_write <= ap_const_logic_1;
        else 
            maskId_val12_c_write <= ap_const_logic_0;
        end if; 
    end process;


    ovrlayId_val11_c_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ovrlayId_val11_c_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ovrlayId_val11_c_blk_n <= ovrlayId_val11_c_full_n;
        else 
            ovrlayId_val11_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayId_val11_c_din <= ovrlayId_val11;

    ovrlayId_val11_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            ovrlayId_val11_c_write <= ap_const_logic_1;
        else 
            ovrlayId_val11_c_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
