-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hdmi_out_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0);
    patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange_val : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef_val : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    height_val4_c12_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    height_val4_c12_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c12_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c12_full_n : IN STD_LOGIC;
    height_val4_c12_write : OUT STD_LOGIC;
    width_val7_c13_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    width_val7_c13_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val7_c13_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val7_c13_full_n : IN STD_LOGIC;
    width_val7_c13_write : OUT STD_LOGIC;
    motionSpeed_val14_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val14_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val14_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val14_c_full_n : IN STD_LOGIC;
    motionSpeed_val14_c_write : OUT STD_LOGIC;
    colorFormat_val17_c14_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val17_c14_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val17_c14_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val17_c14_full_n : IN STD_LOGIC;
    colorFormat_val17_c14_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of hdmi_out_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_4C : STD_LOGIC_VECTOR (7 downto 0) := "01001100";
    constant ap_const_lv8_95 : STD_LOGIC_VECTOR (7 downto 0) := "10010101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv8_6B : STD_LOGIC_VECTOR (7 downto 0) := "01101011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal height_val4_c12_blk_n : STD_LOGIC;
    signal width_val7_c13_blk_n : STD_LOGIC;
    signal motionSpeed_val14_c_blk_n : STD_LOGIC;
    signal colorFormat_val17_c14_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal cmp2_i236_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i236_reg_1232 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i241_fu_669_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i10_i241_reg_1237 : STD_LOGIC_VECTOR (7 downto 0);
    signal not_cmp2_i236_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_cmp2_i236_reg_1242 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i246_fu_683_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i10_i246_reg_1247 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i248_cast_cast_fu_691_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i_i248_cast_cast_reg_1252 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i10_i264_cast_cast_cast_cast_fu_699_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i10_i264_cast_cast_cast_cast_reg_1257 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i_i266_fu_707_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal conv2_i_i_i266_reg_1262 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_fu_715_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_reg_1267 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_5_fu_723_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_5_reg_1272 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidth_reg_1277 : STD_LOGIC_VECTOR (10 downto 0);
    signal barWidthMinSamples_fu_767_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1283 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1288 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_i_i_i_fu_813_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1293 : STD_LOGIC_VECTOR (10 downto 0);
    signal rampStart_load_reg_1298 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_3_reg_1304 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp12_i_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1315 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln563_fu_1022_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln563_reg_1320 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal Sel_reg_1325 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_2_0_0_0217_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_2_0_0_0217_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_1_0_0_0215_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_1_0_0_0215_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_0_0_0_0213_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_0_0_0_0213_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_450_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_446 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_462_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_458 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_474_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_470 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal rampVal_3_new_0_fu_332 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_328 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal_loc_0_fu_324 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hBarSel_4_0_loc_0_fu_320 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr_loc_0_fu_316 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_loc_0_fu_312 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_0_loc_0_fu_308 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hdata_new_0_fu_304 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_300 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2_loc_0_fu_296 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0_loc_0_fu_292 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_2_new_0_fu_288 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_284 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_3_loc_0_fu_280 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_5_0_loc_0_fu_276 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_2_0_0_0218_lcssa227_fu_268 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0216_lcssa224_fu_264 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0214_lcssa221_fu_260 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln750_fu_985_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln563_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_fu_272 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln563_fu_968_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln563_fu_891_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1775_fu_883_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1664_fu_871_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1545_fu_855_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1412_fu_847_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1257_fu_831_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_731_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_i_fu_735_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_751_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_757_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_93_fu_773_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_783_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add5_i_fu_777_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_1_fu_799_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_fu_809_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hdmi_out_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        width_val : IN STD_LOGIC_VECTOR (15 downto 0);
        pix_5 : IN STD_LOGIC_VECTOR (7 downto 0);
        pix : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i266 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i_i248_cast_cast : IN STD_LOGIC_VECTOR (4 downto 0);
        conv2_i_i_i_cast : IN STD_LOGIC_VECTOR (0 downto 0);
        conv2_i_i10_i264_cast_cast_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        conv2_i_i10_i246 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i241 : IN STD_LOGIC_VECTOR (7 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp2_i236 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln1084 : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        width_val_cast31 : IN STD_LOGIC_VECTOR (15 downto 0);
        height_val_cast23 : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln565 : IN STD_LOGIC_VECTOR (15 downto 0);
        empty : IN STD_LOGIC_VECTOR (7 downto 0);
        icmp : IN STD_LOGIC_VECTOR (0 downto 0);
        Sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dpDynamicRange_val : IN STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef_val : IN STD_LOGIC_VECTOR (7 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0217_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0217_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0217_out_o_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0215_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0215_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0215_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0213_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0213_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0213_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_ap_vld : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_0_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_0_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_5_0_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482 : component hdmi_out_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_ready,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_446,
        hdata_flag_0 => hdata_flag_0_reg_458,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_470,
        width_val => width_val,
        pix_5 => pix_5_reg_1272,
        pix => pix_reg_1267,
        conv2_i_i_i266 => conv2_i_i_i266_reg_1262,
        conv2_i_i_i248_cast_cast => conv2_i_i_i248_cast_cast_reg_1252,
        conv2_i_i_i_cast => not_cmp2_i236_reg_1242,
        conv2_i_i10_i264_cast_cast_cast_cast => conv2_i_i10_i264_cast_cast_cast_cast_reg_1257,
        conv2_i_i10_i246 => conv2_i_i10_i246_reg_1247,
        conv2_i_i10_i241 => conv2_i_i10_i241_reg_1237,
        rampStart_1 => rampStart_load_reg_1298,
        ZplateHorContStart_val => ZplateHorContStart_val,
        patternId_val => patternId_val,
        cmp2_i236 => cmp2_i236_reg_1232,
        zext_ln1084 => rampStart_load_reg_1298,
        y => y_3_reg_1304,
        colorFormat_val => colorFormat_val,
        barWidth_cast => barWidth_reg_1277,
        barWidth => barWidth_reg_1277,
        ZplateHorContDelta_val => ZplateHorContDelta_val,
        ZplateVerContStart_val => ZplateVerContStart_val,
        cmp12_i => cmp12_i_reg_1315,
        ZplateVerContDelta_val => ZplateVerContDelta_val,
        sub_i_i_i => sub_i_i_i_reg_1293,
        barWidthMinSamples => barWidthMinSamples_reg_1283,
        width_val_cast31 => width_val,
        height_val_cast23 => height_val,
        zext_ln565 => y_3_reg_1304,
        empty => trunc_ln563_reg_1320,
        icmp => icmp_reg_1288,
        Sel => Sel_reg_1325,
        dpDynamicRange_val => dpDynamicRange_val,
        dpYUVCoef_val => dpYUVCoef_val,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_328,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_324,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_0_loc_1_out_i => hBarSel_4_0_loc_0_fu_320,
        hBarSel_4_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_loc_1_out_o,
        hBarSel_4_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_316,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_312,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_0_loc_1_out_i => hBarSel_0_loc_0_fu_308,
        hBarSel_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_loc_1_out_o,
        hBarSel_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_300,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_296,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_0_loc_1_out_i => hBarSel_3_0_loc_0_fu_292,
        hBarSel_3_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_loc_1_out_o,
        hBarSel_3_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_284,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_280,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_0_loc_1_out_i => hBarSel_5_0_loc_0_fu_276,
        hBarSel_5_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_loc_1_out_o,
        hBarSel_5_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_loc_1_out_o_ap_vld,
        p_0_2_0_0_0217_out_i => p_0_2_0_0_0218_lcssa227_fu_268,
        p_0_2_0_0_0217_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_2_0_0_0217_out_o,
        p_0_2_0_0_0217_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_2_0_0_0217_out_o_ap_vld,
        p_0_1_0_0_0215_out_i => p_0_1_0_0_0216_lcssa224_fu_264,
        p_0_1_0_0_0215_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_1_0_0_0215_out_o,
        p_0_1_0_0_0215_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_1_0_0_0215_out_o_ap_vld,
        p_0_0_0_0_0213_out_i => p_0_0_0_0_0214_lcssa221_fu_260,
        p_0_0_0_0_0213_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_0_0_0_0213_out_o,
        p_0_0_0_0_0213_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_0_0_0_0213_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_ap_vld,
        hBarSel_4_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0,
        hBarSel_4_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_ap_vld,
        s => s,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_ap_vld,
        hBarSel_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0,
        hBarSel_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_ap_vld,
        hBarSel_3_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0,
        hBarSel_3_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_ap_vld,
        hBarSel_5_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0,
        hBarSel_5_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_0_loc_0_fu_308_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_0_loc_0_fu_308 <= zext_ln1545_fu_855_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_0_loc_0_fu_308 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_3_0_loc_0_fu_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_3_0_loc_0_fu_292 <= zext_ln1664_fu_871_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_3_0_loc_0_fu_292 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_0_loc_0_fu_320_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_4_0_loc_0_fu_320 <= hBarSel_4_0;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_4_0_loc_0_fu_320 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_0_loc_0_fu_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hBarSel_5_0_loc_0_fu_276 <= zext_ln563_fu_891_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_5_0_loc_0_fu_276 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_458_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                hdata_flag_0_reg_458 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_flag_1_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hdata_flag_0_reg_458 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                hdata_loc_0_fu_300 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hdata_loc_0_fu_300 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_470_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_2_flag_0_reg_470 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_flag_1_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_2_flag_0_reg_470 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_2_loc_0_fu_284 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_2_loc_0_fu_284 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_446_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_3_flag_0_reg_446 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_flag_1_out;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_3_flag_0_reg_446 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_3_loc_0_fu_328 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_3_loc_0_fu_328 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                rampVal_loc_0_fu_324 <= zext_ln1257_fu_831_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_loc_0_fu_324 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_296_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                vBarSel_2_loc_0_fu_296 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_2_loc_0_fu_296 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_280_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                vBarSel_3_loc_0_fu_280 <= zext_ln1775_fu_883_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_3_loc_0_fu_280 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                vBarSel_loc_0_fu_312 <= zext_ln1412_fu_847_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_loc_0_fu_312 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                y_fu_272 <= ap_const_lv16_0;
            elsif (((icmp_ln563_fu_963_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_272 <= add_ln563_fu_968_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                zonePlateVAddr_loc_0_fu_316 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                zonePlateVAddr_loc_0_fu_316 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                Sel_reg_1325 <= y_3_reg_1304(7 downto 6);
                trunc_ln563_reg_1320 <= trunc_ln563_fu_1022_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                barWidthMinSamples_reg_1283 <= barWidthMinSamples_fu_767_p2;
                barWidth_reg_1277 <= add_i_fu_735_p2(13 downto 3);
                cmp2_i236_reg_1232 <= cmp2_i236_fu_663_p2;
                    conv2_i_i10_i241_reg_1237(1 downto 0) <= conv2_i_i10_i241_fu_669_p3(1 downto 0);    conv2_i_i10_i241_reg_1237(5 downto 4) <= conv2_i_i10_i241_fu_669_p3(5 downto 4);    conv2_i_i10_i241_reg_1237(7) <= conv2_i_i10_i241_fu_669_p3(7);
                    conv2_i_i10_i246_reg_1247(0) <= conv2_i_i10_i246_fu_683_p3(0);    conv2_i_i10_i246_reg_1247(2) <= conv2_i_i10_i246_fu_683_p3(2);    conv2_i_i10_i246_reg_1247(4) <= conv2_i_i10_i246_fu_683_p3(4);    conv2_i_i10_i246_reg_1247(7) <= conv2_i_i10_i246_fu_683_p3(7);
                    conv2_i_i10_i264_cast_cast_cast_cast_reg_1257(0) <= conv2_i_i10_i264_cast_cast_cast_cast_fu_699_p3(0);    conv2_i_i10_i264_cast_cast_cast_cast_reg_1257(2) <= conv2_i_i10_i264_cast_cast_cast_cast_fu_699_p3(2);
                    conv2_i_i_i248_cast_cast_reg_1252(0) <= conv2_i_i_i248_cast_cast_fu_691_p3(0);    conv2_i_i_i248_cast_cast_reg_1252(2) <= conv2_i_i_i248_cast_cast_fu_691_p3(2);    conv2_i_i_i248_cast_cast_reg_1252(4) <= conv2_i_i_i248_cast_cast_fu_691_p3(4);
                    conv2_i_i_i266_reg_1262(2) <= conv2_i_i_i266_fu_707_p3(2);    conv2_i_i_i266_reg_1262(4) <= conv2_i_i_i266_fu_707_p3(4);    conv2_i_i_i266_reg_1262(7) <= conv2_i_i_i266_fu_707_p3(7);
                icmp_reg_1288 <= icmp_fu_793_p2;
                not_cmp2_i236_reg_1242 <= not_cmp2_i236_fu_677_p2;
                    pix_5_reg_1272(6 downto 0) <= pix_5_fu_723_p3(6 downto 0);
                    pix_reg_1267(7) <= pix_fu_715_p3(7);
                rampStart_load_reg_1298 <= rampStart;
                sub_i_i_i_reg_1293 <= sub_i_i_i_fu_813_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp12_i_reg_1315 <= cmp12_i_fu_974_p2;
                y_3_reg_1304 <= y_fu_272;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_3_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hBarSel_5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_phi_mux_hdata_flag_0_phi_fu_462_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                hdata <= hdata_new_0_fu_304;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hdata_new_0_fu_304 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_0_0_0_0213_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_0214_lcssa221_fu_260 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_0_0_0_0213_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_1_0_0_0215_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_0216_lcssa224_fu_264 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_1_0_0_0215_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_2_0_0_0217_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_0218_lcssa227_fu_268 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_p_0_2_0_0_0217_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampStart <= add_ln750_fu_985_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_3_flag_0_phi_fu_450_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_1 <= rampVal_3_new_0_fu_332;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_2_flag_0_phi_fu_474_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_2 <= rampVal_2_new_0_fu_288;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_2_new_0_fu_288 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_3_new_0_fu_332 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_zonePlateVAddr;
            end if;
        end if;
    end process;
    conv2_i_i10_i241_reg_1237(3 downto 2) <= "11";
    conv2_i_i10_i241_reg_1237(6) <= '1';
    conv2_i_i10_i246_reg_1247(1) <= '0';
    conv2_i_i10_i246_reg_1247(3 downto 3) <= "0";
    conv2_i_i10_i246_reg_1247(6 downto 5) <= "00";
    conv2_i_i_i248_cast_cast_reg_1252(1) <= '0';
    conv2_i_i_i248_cast_cast_reg_1252(3) <= '0';
    conv2_i_i10_i264_cast_cast_cast_cast_reg_1257(1) <= '0';
    conv2_i_i_i266_reg_1262(1 downto 0) <= "11";
    conv2_i_i_i266_reg_1262(3 downto 3) <= "1";
    conv2_i_i_i266_reg_1262(6 downto 5) <= "11";
    pix_reg_1267(6 downto 0) <= "0000000";
    pix_5_reg_1272(7) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_done, ap_CS_fsm_state4, icmp_ln563_fu_963_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add2_i_fu_751_p2 <= std_logic_vector(unsigned(empty_fu_731_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_777_p2 <= std_logic_vector(unsigned(empty_93_fu_773_p1) + unsigned(ap_const_lv14_F));
    add_i_fu_735_p2 <= std_logic_vector(unsigned(empty_fu_731_p1) + unsigned(ap_const_lv14_7));
    add_ln563_fu_968_p2 <= std_logic_vector(unsigned(y_fu_272) + unsigned(ap_const_lv16_1));
    add_ln750_fu_985_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(motionSpeed_val));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val4_c12_full_n, width_val7_c13_full_n, motionSpeed_val14_c_full_n, colorFormat_val17_c14_full_n)
    begin
                ap_block_state1 <= ((colorFormat_val17_c14_full_n = ap_const_logic_0) or (motionSpeed_val14_c_full_n = ap_const_logic_0) or (width_val7_c13_full_n = ap_const_logic_0) or (height_val4_c12_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln563_fu_963_p2)
    begin
        if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_462_p4 <= hdata_flag_0_reg_458;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_474_p4 <= rampVal_2_flag_0_reg_470;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_450_p4 <= rampVal_3_flag_0_reg_446;

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln563_fu_963_p2)
    begin
        if (((icmp_ln563_fu_963_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    barHeight_cast_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_799_p4),11));
    barWidthMinSamples_fu_767_p2 <= std_logic_vector(unsigned(p_cast_fu_757_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp12_i_fu_974_p2 <= "0" when (y_fu_272 = ap_const_lv16_0) else "1";
    cmp2_i236_fu_663_p2 <= "1" when (colorFormat_val = ap_const_lv8_0) else "0";

    colorFormat_val17_c14_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val17_c14_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val17_c14_blk_n <= colorFormat_val17_c14_full_n;
        else 
            colorFormat_val17_c14_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    colorFormat_val17_c14_din <= colorFormat_val;

    colorFormat_val17_c14_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            colorFormat_val17_c14_write <= ap_const_logic_1;
        else 
            colorFormat_val17_c14_write <= ap_const_logic_0;
        end if; 
    end process;

    conv2_i_i10_i241_fu_669_p3 <= 
        ap_const_lv8_FF when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv8_4C;
    conv2_i_i10_i246_fu_683_p3 <= 
        ap_const_lv8_0 when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv8_95;
    conv2_i_i10_i264_cast_cast_cast_cast_fu_699_p3 <= 
        ap_const_lv3_0 when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv3_5;
    conv2_i_i_i248_cast_cast_fu_691_p3 <= 
        ap_const_lv5_0 when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv5_15;
    conv2_i_i_i266_fu_707_p3 <= 
        ap_const_lv8_FF when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv8_6B;
    empty_93_fu_773_p1 <= height_val(14 - 1 downto 0);
    empty_fu_731_p1 <= width_val(14 - 1 downto 0);
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_482_ap_start_reg;

    height_val4_c12_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val4_c12_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c12_blk_n <= height_val4_c12_full_n;
        else 
            height_val4_c12_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val4_c12_din <= height_val;

    height_val4_c12_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            height_val4_c12_write <= ap_const_logic_1;
        else 
            height_val4_c12_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_fu_793_p2 <= "0" when (tmp_fu_783_p4 = ap_const_lv7_0) else "1";
    icmp_ln563_fu_963_p2 <= "1" when (y_fu_272 = height_val) else "0";

    motionSpeed_val14_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, motionSpeed_val14_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val14_c_blk_n <= motionSpeed_val14_c_full_n;
        else 
            motionSpeed_val14_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    motionSpeed_val14_c_din <= motionSpeed_val;

    motionSpeed_val14_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            motionSpeed_val14_c_write <= ap_const_logic_1;
        else 
            motionSpeed_val14_c_write <= ap_const_logic_0;
        end if; 
    end process;

    not_cmp2_i236_fu_677_p2 <= (cmp2_i236_fu_663_p2 xor ap_const_lv1_1);
    p_cast_fu_757_p4 <= add2_i_fu_751_p2(13 downto 4);
    pix_5_fu_723_p3 <= 
        ap_const_lv8_FF when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv8_80;
    pix_fu_715_p3 <= 
        ap_const_lv8_0 when (cmp2_i236_fu_663_p2(0) = '1') else 
        ap_const_lv8_80;
    sub_i_i_i_fu_813_p2 <= std_logic_vector(unsigned(barHeight_cast_fu_809_p1) + unsigned(ap_const_lv11_7FF));
    tmp_1_fu_799_p4 <= add5_i_fu_777_p2(13 downto 4);
    tmp_fu_783_p4 <= colorFormat_val(7 downto 1);
    trunc_ln563_fu_1022_p1 <= y_3_reg_1304(8 - 1 downto 0);

    width_val7_c13_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val7_c13_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val7_c13_blk_n <= width_val7_c13_full_n;
        else 
            width_val7_c13_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val7_c13_din <= width_val;

    width_val7_c13_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            width_val7_c13_write <= ap_const_logic_1;
        else 
            width_val7_c13_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1257_fu_831_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1412_fu_847_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1545_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_0),8));
    zext_ln1664_fu_871_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3_0),8));
    zext_ln1775_fu_883_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln563_fu_891_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_5_0),8));
end behav;
